#Numpy
It is a package or module to perform specific computing in python efficienlty. It works only numerical data.

In [1]:
#installing numpy
!pip install -q numpy

In [2]:
#Numpy Arrays

#list of put volume data in lacs
put_vol = [52.89, 45.14, 63.84, 77.1, 74.6]

#list of call volume in lacs
call_vol = [49.41, 50.45, 59.11, 80.49, 65.11]

In [3]:
import numpy as np

n_put_vol = np.array(put_vol)
n_call_vol = np.array(call_vol)

n_put_vol/n_call_vol

array([1.07043109, 0.89474727, 1.0800203 , 0.95788297, 1.14575334])

In [4]:
#rank 1 array
arr1=np.array([1,2,3])
print (arr1,type(arr1))

[1 2 3] <class 'numpy.ndarray'>


In [5]:
#shape gives the shape of the array
arr1.shape

(3,)

In [6]:
arr1[0],arr1[1],arr1[2]

(1, 2, 3)

In [7]:
arr1[1]=4
arr1

array([1, 4, 3])

In [8]:
#rank 2 array
arr2 =np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
arr2.shape

(2, 3)

In [10]:
#zeros(shape, dtype): returns an array of given shape and dtype, filled with zeroes
#creating 1-d array
np.zeros(5) 

array([0., 0., 0., 0., 0.])

In [11]:
#creating array of ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
#create a 2D array.
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
#ones(shape, dtype): returns an array of given shape and dtype, filled with ones 
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
#full(shape, fill_value): returns an array of given shape and dtype, filled with fill_value given as parameter
np.full((2,3),1)

array([[1, 1, 1],
       [1, 1, 1]])

In [15]:
np.full((5,5),58)

array([[58, 58, 58, 58, 58],
       [58, 58, 58, 58, 58],
       [58, 58, 58, 58, 58],
       [58, 58, 58, 58, 58],
       [58, 58, 58, 58, 58]])

In [16]:
#arange([start,] stop-1, [step]): This returns an array with evenly spaced values within a given interval
np.arange(5)

array([0, 1, 2, 3, 4])

In [17]:
np.arange(1,5,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [18]:
#linspace(start, stop, num, endpoint): returns evenly spaced numbers over a specified interval
np.linspace(2.0, 3.0, num=10)


array([2.        , 2.11111111, 2.22222222, 2.33333333, 2.44444444,
       2.55555556, 2.66666667, 2.77777778, 2.88888889, 3.        ])

In [19]:
np.linspace(2.0, 3.0, num=10, endpoint=False)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [20]:
np.linspace(2.0, 3.0, num=10, endpoint=True)

array([2.        , 2.11111111, 2.22222222, 2.33333333, 2.44444444,
       2.55555556, 2.66666667, 2.77777778, 2.88888889, 3.        ])

In [21]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
np.eye(4,k=0)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#Random Sampling


In [23]:
#rand():It is used to create an array of a given shape and populate it with random samples,
#from a uniform distribution over[0,1]. It takes only positive arguments

np.random.rand()

0.4607722051542138

In [24]:
#1D array
np.random.rand(4)

array([0.88220406, 0.80037723, 0.63179821, 0.91207296])

In [25]:
#2D array
np.random.rand(2,3)

array([[0.18326876, 0.82929329, 0.56694232],
       [0.69916676, 0.75433149, 0.71860433]])

In [26]:
#randn():
np.random.randn()

0.505065865009097

In [27]:
np.random.randn(2,3)

array([[-0.45407581, -1.50394114, -0.65468671],
       [ 1.08829307, -0.94032231, -2.28713492]])

In [28]:
#randint():
np.random.randint(50)

2

In [29]:
#1D array (start, end, size)
np.random.randint(6,12,3)

array([11, 10,  7])

#Array attributes and methods

In [30]:
#ndim
n_call_vol.ndim

1

In [31]:
arr2.ndim

2

In [32]:
arr2.shape

(2, 3)

#Array Indexing
numpy offers several ways to index into arrays

In [33]:
#slicing
arr1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [34]:
arr2=arr1[:2,1:3]
arr2

array([[2, 3],
       [6, 7]])

In [35]:
x=np.array([1,2])
print (x.dtype)

int64


In [36]:
ar = np.arange(12)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [37]:
np.reshape(ar,(3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
x+y

array([[ 6,  8],
       [10, 12]])

#Broadcasting
It is a powerful mechanism which allows numpy to work with arrays of different shapes when performing arithmetic operations. 

In [39]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [40]:
v = np.array([1,0,1])

In [41]:
y = np.empty_like(x)
for i in range(4):
  y[i,:] = x[i,:]+v
y

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])